### ISSUE TITLE
Coin graph

### ISSUE THREAD

**Issue by shubhamzanwar** [shubhamzanwar/cryptocoin-folio#4]
Displays the live value of the coin chosen on the left half of the page. Both the public and the signed in user may view this graph.
The user may choose a coin from the ticker on the right half of the page. Default coin is Ripple(XRP)

**Comment by parthsr** [comment]
Both the graphs should be different stories right?

**Comment by shubhamzanwar** [comment]
I feel they belong together.

**Comment by parthsr** [comment]
Both the graphs work independently. They should be in different stories.

**Comment by shubhamzanwar** [comment]
Feel free to change, in that case.
